# Generated by Django 5.0.7 on 2026-07-09 20:03

import apps.screenshots.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to=apps.screenshots.models.screenshot_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.screenshots.models.thumbnail_path)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('capture_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=12)),
                ('active_application', models.CharField(blank=True, max_length=200)),
                ('active_window_title', models.CharField(blank=True, max_length=255)),
                ('active_website', models.CharField(blank=True, max_length=255)),
                ('activity_level', models.PositiveSmallIntegerField(default=0, help_text='0-100 activity intensity at capture time.')),
                ('is_blurred', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('monitor_number', models.PositiveSmallIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='employees.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='monitoring.activitysession')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['employee', '-captured_at'], name='screenshots_employe_b4b7ae_idx'), models.Index(fields=['is_flagged'], name='screenshots_is_flag_ec8a58_idx')],
            },
        ),
    ]
