# Generated by Django 5.0.7 on 2026-07-09 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company_name', models.CharField(default='Acme Corporation', max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #2563eb.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('accent_color', models.CharField(default='#7c3aed', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex colour, e.g. #2563eb.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')])),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('date_format', models.CharField(default='Y-m-d', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=4)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1)),
                ('screenshots_enabled', models.BooleanField(default=True)),
                ('screenshot_interval_seconds', models.PositiveIntegerField(default=600)),
                ('screenshot_blur_enabled', models.BooleanField(default=True)),
                ('activity_tracking_enabled', models.BooleanField(default=True)),
                ('idle_threshold_seconds', models.PositiveIntegerField(default=300)),
                ('gps_validation_enabled', models.BooleanField(default=False)),
                ('enforce_2fa', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=90)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('max_login_attempts', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Company settings',
                'verbose_name_plural': 'Company settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('days_per_year', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=False)),
                ('color', models.CharField(default='#0ea5e9', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='Standard Hours', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('break_minutes', models.PositiveIntegerField(default=60)),
                ('daily_hours', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
                ('flexible', models.BooleanField(default=False)),
                ('grace_period_minutes', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Working hours policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='Company Holidays', max_length=120)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='settings_app.holidaycalendar')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=160)),
                ('pattern', models.CharField(help_text='Application name or website domain to match.', max_length=200)),
                ('category', models.CharField(choices=[('productive', 'Productive'), ('neutral', 'Neutral'), ('unproductive', 'Unproductive')], default='neutral', max_length=16)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productivity_rules', to='employees.department')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
