# Generated by Django 5.0.7 on 2026-07-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('target_score', models.FloatField(default=75)),
                ('target_hours', models.DecimalField(decimal_places=2, default=40, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_goals', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True)),
                ('productivity_score', models.FloatField(default=0)),
                ('activity_score', models.FloatField(default=0)),
                ('focus_score', models.FloatField(default=0)),
                ('efficiency_score', models.FloatField(default=0)),
                ('attendance_score', models.FloatField(default=0)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('focus_seconds', models.PositiveIntegerField(default=0)),
                ('break_seconds', models.PositiveIntegerField(default=0)),
                ('meeting_seconds', models.PositiveIntegerField(default=0)),
                ('productive_seconds', models.PositiveIntegerField(default=0)),
                ('neutral_seconds', models.PositiveIntegerField(default=0)),
                ('unproductive_seconds', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', '-date'], name='productivit_employe_84fc28_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
