"""Tests for the projects app."""
from __future__ import annotations

from django.test import TestCase

from apps.projects.models import Project, ProjectStatus


class ProjectTests(TestCase):
    def test_slug_and_code_autogenerated(self):
        project = Project.objects.create(name="Website Redesign")
        self.assertTrue(project.slug)
        self.assertTrue(project.code.startswith("PRJ-"))

    def test_budget_used_percent(self):
        project = Project.objects.create(name="Budget Test", budget=1000, spent=250)
        self.assertEqual(project.budget_used_percent, 25.0)

    def test_health_indicator(self):
        project = Project.objects.create(
            name="Healthy", status=ProjectStatus.ACTIVE, progress=80, budget=1000, spent=100
        )
        self.assertEqual(project.health, "success")

    def test_overdue(self):
        import datetime

        project = Project.objects.create(
            name="Late",
            status=ProjectStatus.ACTIVE,
            due_date=datetime.date(2000, 1, 1),
        )
        self.assertTrue(project.is_overdue)
