# Generated by Django 5.0.7 on 2026-07-09 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('break_seconds', models.PositiveIntegerField(default=0)),
                ('meeting_seconds', models.PositiveIntegerField(default=0)),
                ('keyboard_events', models.PositiveIntegerField(default=0)),
                ('mouse_events', models.PositiveIntegerField(default=0)),
                ('mouse_distance', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=120)),
                ('operating_system', models.CharField(blank=True, max_length=80)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('is_vpn', models.BooleanField(default=False)),
                ('monitor_count', models.PositiveSmallIntegerField(default=1)),
                ('timezone_name', models.CharField(blank=True, max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to='employees.employee')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('active_application', models.CharField(blank=True, max_length=200)),
                ('active_window_title', models.CharField(blank=True, max_length=255)),
                ('active_website', models.CharField(blank=True, max_length=255)),
                ('keyboard_events', models.PositiveIntegerField(default=0)),
                ('mouse_events', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_snapshots', to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.activitysession')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True)),
                ('application', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('productive', 'Productive'), ('neutral', 'Neutral'), ('unproductive', 'Unproductive')], default='neutral', max_length=16)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_usage', to='employees.employee')),
            ],
            options={
                'ordering': ['-seconds'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField(default=0)),
                ('ram_percent', models.FloatField(default=0)),
                ('disk_percent', models.FloatField(default=0)),
                ('battery_percent', models.FloatField(blank=True, null=True)),
                ('is_charging', models.BooleanField(default=False)),
                ('network_status', models.CharField(blank=True, max_length=40)),
                ('download_mbps', models.FloatField(default=0)),
                ('upload_mbps', models.FloatField(default=0)),
                ('ping_ms', models.FloatField(default=0)),
                ('usb_devices', models.PositiveSmallIntegerField(default=0)),
                ('printer_jobs', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_metrics', to='employees.employee')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.activitysession')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True)),
                ('domain', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('productive', 'Productive'), ('neutral', 'Neutral'), ('unproductive', 'Unproductive')], default='neutral', max_length=16)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_usage', to='employees.employee')),
            ],
            options={
                'ordering': ['-seconds'],
            },
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['employee', '-started_at'], name='monitoring__employe_974457_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationusage',
            unique_together={('employee', 'date', 'application')},
        ),
        migrations.AlterUniqueTogether(
            name='websiteusage',
            unique_together={('employee', 'date', 'domain')},
        ),
    ]
