# Generated by Django 5.0.7 on 2026-07-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('headcount', models.PositiveIntegerField(default=0)),
                ('active_employees', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('avg_productivity', models.FloatField(default=0)),
                ('avg_activity', models.FloatField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('overtime_hours', models.FloatField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('active_projects', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'KPI snapshot',
                'verbose_name_plural': 'KPI snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
